### ISSUE TITLE
Frontend for Escrow contracts

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-ui#26]
### Motivation

We need a user interface for the escrow contracts.

### Task List
- [x] #27 
- [x] #29
- [ ] #30
- [ ] #35
- [ ] #28
- [ ] #31
- [ ] #32
- [ ] #33
- [ ] #34

**Comment by matt-user** [comment]
- [ ] #27 
- [ ] #29
- [ ] #30
- [ ] #35
- [ ] #28
- [ ] #31
- [ ] #32
- [ ] #33
- [ ] #34

**Comment by Braqzen** [comment]
> * [ ]  [Feat: basic project setup #27](https://github.com/FuelLabs/fuels-ui/issues/27)
> * [ ]  [Feat: allow the user to create multiple wallets #29](https://github.com/FuelLabs/fuels-ui/issues/29)
> * [ ]  [Chore: copy the smart contracts into the contracts directory under escrow #30](https://github.com/FuelLabs/fuels-ui/issues/30)
> * [ ]  [Feat: allow users to make contract calls with both created wallets #35](https://github.com/FuelLabs/fuels-ui/issues/35)
> * [ ]  [Feat: allow the user to mint tokens #28](https://github.com/FuelLabs/fuels-ui/issues/28)
> * [ ]  [Feat: allow a user to create escrow contracts #31](https://github.com/FuelLabs/fuels-ui/issues/31)
> * [ ]  [Feat: allow escrow users to deposit assets #32](https://github.com/FuelLabs/fuels-ui/issues/32)
> * [ ]  [Feat: add button to allow users to approve the escrow #33](https://github.com/FuelLabs/fuels-ui/issues/33)
> * [ ]  [Feat: add button to withdraw funds from the escrow #34](https://github.com/FuelLabs/fuels-ui/issues/34)

If you move these into the description then github will add some fancy tracking to it.
You can also create a "milestone" and add the issues under that
